GET http://127.0.0.1:8000/hello/

###
POST http://127.0.0.1:8000/hello/
content-type: application/json

{
    "sdfsf": "sdffr",
    "fsdfs": "asr"
}

###
GET http://127.0.0.1:8000/cats/

###
GET http://127.0.0.1:8000/cat/1/

###
POST http://127.0.0.1:8000/cats/
content-type: application/json

{
    "name": "Phfurupsik",
    "color": "magnetts",
    "birth_year": 2024
}

###
PATCH http://127.0.0.1:8000/cat/4/
content-type: application/json

{
    "name": "hgfdyh",
    "color": "white"
}